"""add stock restored flag to orders

Revision ID: 029b35030d14
Revises: a8ca756ff570
Create Date: 2026-08-11 00:10:40.143967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029b35030d14'
down_revision = 'a8ca756ff570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_restored', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('stock_restored')

    # ### end Alembic commands ###
