"""Add product active status

Revision ID: 16916ab3fea3
Revises: 029b35030d14
Create Date: 2026-08-14 20:47:22.534882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16916ab3fea3'
down_revision = '029b35030d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
