"""Product details fields added

Revision ID: 809de3e89b65
Revises: 71d2d3fdfd03
Create Date: 2026-08-06 21:25:58.683450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809de3e89b65'
down_revision = '71d2d3fdfd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('long_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('leather_type', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hardware', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('lining', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('dimensions', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('made_in', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('warranty', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('care', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_bestseller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_bestseller')
        batch_op.drop_column('care')
        batch_op.drop_column('warranty')
        batch_op.drop_column('made_in')
        batch_op.drop_column('weight')
        batch_op.drop_column('dimensions')
        batch_op.drop_column('lining')
        batch_op.drop_column('hardware')
        batch_op.drop_column('leather_type')
        batch_op.drop_column('long_description')
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
